### PR TITLE
Added ios version

### PR DESCRIPTION
**Pull request by JarrodLodge**
Added an iOs version so that the application would still build. This allows me to use a different process for iOs but still the same code base for Android. In the application i can check if platform is Android and use this pluign, if iOs use another plugin. Application wouldn't build for iOs before this fix.
First pull request, so let me know if i've done anything wrong. :)

### CODE REVIEW

**Comment by julien-h** [comment]
Hi Jarrod,
The only modified file that I see in your commit is "android/gradle/wrapper/gradle-wrapper.properties"

How does this impact ios?

**Comment by JarrodLodge** [comment]
Hi Julien, I might of mucked it up. But what i did was trying to do was to start working on the iOs version of my app. But because Foreground service was missing the generated iOs code it  wouldn't build at all. My thoughts were i would get it to build and then use platform.isAndroid to switch inside the app.
All i did for this pull request was regenerate the plugin which generated the iOs code needed to atleast build, which it did.

**Comment by JarrodLodge** [comment]
Hi Julien, found the reason. The iOs folder was in the gitignore file. Just to be clear, this doesn't make the plugin work in iOs. It just allows it to be built so we can switch dependacies based on platform inside our fluttter app.

**Comment by julien-h** [comment]
Thanks Jarrod, 
I intend to use `Platform.isAndroid` too.

Hopefully, @michael-cheung-thebus can merge this so that the app can compile on iOS.

Out of curiosity, what plugin do you use for the iOS version?

**Comment by JarrodLodge** [comment]
Hi Julien,
My plan was to run everything inside an isolate for iOs. I've actually got more budget for our project and have hired a native iOs/Android developer, so have moved away from Flutter for now.
https://pub.dev/packages/flutter_isolate Was going to try this.

**Comment by michael-cheung-thebus** [comment]
Thanks, Jarrod.  After reviewing both this and #25, they both still had way too much stuff just to add build support for a platform this plugin doesn't even work on (of course that's not your fault - [Flutter #10530](https://github.com/flutter/flutter/issues/10530) really needs to be resolved).

If you ever end up returning to Flutter (and this plugin), hopefully v2.0.1 will meet your needs.

**Pull request closed without merging**
